# Generated by Django 4.0 on 2023-05-12 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_staff_github_link_alter_staff_instagram_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='portfolio',
            field=models.CharField(blank=True, default='https://', max_length=2048, null=True, unique=True, verbose_name='Portfolio Link'),
        ),
    ]
